---
# tasks file for nginx
- name: Changing Nginx client max body size Value
  ansible.builtin.lineinfile:
    path: "{{ lb2193_aap_caac_nginx_conf_path }}"
    regexp: '.*client_max_body_size 5m;'
    line: '        client_max_body_size 100m;'
  become: true
  notify: Restart Nginx
