---
# tasks file for aap
- name: Clone of a github branch
  ansible.builtin.git:
    repo: '{{ lb2193_aap_caac_aap_github_repo }}'
    dest: '{{ lb2193_aap_caac_aap_clone_destination_path }}'
    single_branch: yes
    version: '{{ lb2193_aap_caac_aap_github_version }}'
  become: yes
  become_user: "{{ lb2193_aap_caac_aap_ssh_username }}"
    
- name: Ensure ansible.cfg exists
  ansible.builtin.file:
    path: "{{ lb2193_aap_caac_aap_ansible_cfg_path }}ansible.cfg"
    state: touch
    mode: "0644"
    owner: "{{ lb2193_aap_caac_aap_ssh_username }}"
    group: "{{ lb2193_aap_caac_aap_ssh_username }}"

- name: Install ansible-lint python package
  ansible.builtin.pip:
    name: ansible-lint
    name:
      - ansible-lint
      - awxkit

- name: Configure ansible.cfg for Private Automation Hub
  ansible.builtin.blockinfile:
    path: "{{ lb2193_aap_caac_aap_ansible_cfg_path }}ansible.cfg"
    block: |
      [defaults]
      vault_password_file=.password
      [galaxy]
      server_list = {{ lb2193_aap_caac_aap_private_ah_repos | map(attribute='name') | join(', ') }}

      {% for repo in lb2193_aap_caac_aap_private_ah_repos %}
      [galaxy_server.{{ repo.name }}]
      url={{ repo.url }}
      username={{ lb2193_aap_caac_aap_private_ah_username }}
      password={{ lb2193_aap_caac_aap_private_ah_password }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED PRIVATE AUTOMATION HUB CONFIGURATION"

- name: Include collection remote role
  ansible.builtin.include_role:
    name: infra.aap_configuration.hub_collection_remote
  vars:
    hub_collection_remotes: '{{ lb2193_aap_caac_aap_hub_collection_remotes }}'

- name: Include collection repository role
  ansible.builtin.include_role:
    name: infra.aap_configuration.hub_collection_repository
  vars:
    hub_collection_repositories: '{{ lb2193_aap_caac_aap_hub_collection_repositories }}'

- name: Include collection repository role
  ansible.builtin.include_role:
    name: infra.aap_configuration.hub_collection_repository_sync
  vars:
    hub_collection_repositories: '{{ lb2193_aap_caac_aap_hub_collection_repositories }}'
    hub_configuration_collection_repository_sync_async_delay: 5
    hub_configuration_collection_repository_sync_async_retries: 150

- name: Install specific Ansible collections
  ansible.builtin.command: "ANSIBLE_CONFIG={{ lb2193_aap_caac_aap_ansible_cfg_path }}ansible.cfg ansible-galaxy collection install {{ item }}"
  loop: "{{ lb2193_aap_caac_aap_collections_list }}"
  args:
    chdir: "{{ lb2193_aap_caac_aap_ansible_cfg_path }}"
  when: lb2193_aap_caac_aap_collections_list | length > 0
  ignore_errors: yes

- name: configure auth.yml file
  ansible.builtin.blockinfile:
    path: "{{ lb2193_aap_caac_aap_ansible_cfg_path }}/group_vars/all/auth.yml"
    block: |
      aap_hostname: "{{ lb2193_aap_caac_aap_hostname | regex_replace('^https://', '') }}"
      aap_username: "{{ lb2193_aap_caac_aap_username }}"
      aap_password: "{{ lb2193_aap_caac_aap_password }}"
      aap_validate_certs: false
      aap_request_timeout: 60
      
      ee_pull_collections_from_hub: false
      aap_service_account_username: aap_service_account

      ee_registry_username: "{{ lb2193_aap_caac_aap_username }} "
      ee_registry_password: "{{ lb2193_aap_caac_aap_password }}"

      ee_registry_dest: "{{ lb2193_aap_caac_aap_hostname | regex_replace('^https://', '') }}/config"
      ee_base_registry: "{{ lb2193_aap_caac_aap_hostname | regex_replace('^https://', '') }}"
      
      ee_base_registry_username: "{{ lb2193_aap_caac_aap_username }}"
      ee_base_registry_password: "{{ lb2193_aap_caac_aap_password }}"
      
      ee_validate_certs: false
    marker: "# {mark} ANSIBLE MANAGED Variable configuration"

- name: Ensure Vautl.yml exists
  ansible.builtin.file:
    path: "{{ lb2193_aap_caac_aap_ansible_cfg_path }}vautl.yml"
    state: touch
    mode: "0644"
    owner: "{{ lb2193_aap_caac_aap_ssh_username }}"
    group: "{{ lb2193_aap_caac_aap_ssh_username }}"
    
- name: configure Vautl.yml file
  ansible.builtin.blockinfile:
    path: "{{ lb2193_aap_caac_aap_ansible_cfg_path }}vault.yml"
    block: |
      vault_pass: "{{ lb2193_aap_caac_aap_password }}"
      aap_password: "{{ lb2193_aap_caac_aap_password }}"
      machine_pass: "{{ lb2193_aap_caac_aap_password }}"
      aap_service_account_password: "{{ lb2193_aap_caac_aap_password }}"
      student_account: "{{ lb2193_aap_caac_aap_password }}"
    marker: "# {mark} ANSIBLE MANAGED Variable configuration"
